# Copyright (c) 2025 By David "Hankinsohl" Hankins.
# This software is licensed under the terms of the MIT License.
# Created by Hankinsohl on 7/25/2025.
[package]
name = "hankinsohl_utils"
version = "0.0.1-alpha.1"
edition = "2024"

